@extends('layouts.simple')

@section('title', 'Privacy Policy')

@section('backRoute', route('home'))

@section('content')

    @php
        $sections = [
            [
                'heading' => 'Information We Collect',
                'paragraphs' => [
                    'When you create an account, we collect your phone number, name, and, if you sign in with Google, your Google profile name and email address.',
                    'We also collect information generated by using the app, such as your deposits, withdrawals, wallet balance, investment plan activity, and referral history.',
                ],
            ],
            [
                'heading' => 'How We Use Your Information',
                'paragraphs' => [
                    'We use your information to create and secure your account, process deposits and withdrawals, show your portfolio and returns, and calculate referral rewards you may be eligible for.',
                    'We may also use your phone number to send one-time passwords (OTPs) and important account or transaction notifications.',
                ],
            ],
            [
                'heading' => 'Data Sharing & Third Parties',
                'paragraphs' => [
                    'We do not sell your personal information. We share only what is necessary with trusted providers who help us operate GullakPe, such as Google (for Google Sign-In) and payment/UPI processing partners.',
                    'We may disclose information if required by law or to protect the rights, property, or safety of GullakPe, our users, or the public.',
                ],
            ],
            [
                'heading' => 'Data Security',
                'paragraphs' => [
                    'Your MPIN is stored in encrypted (hashed) form and is never visible to us in plain text. We use industry-standard practices to protect your account, including OTP verification and progressive lockouts after repeated failed login attempts.',
                ],
            ],
            [
                'heading' => 'Data Retention',
                'paragraphs' => [
                    'We retain your account and transaction information for as long as your account is active, and for a reasonable period afterward as required for legal, accounting, or fraud-prevention purposes.',
                ],
            ],
            [
                'heading' => 'Your Rights & Choices',
                'paragraphs' => [
                    'You can update certain profile details from the Settings page in the app, and you can choose your preferred display language (English or Hindi) at any time using the translate option.',
                    'To request access to, correction of, or deletion of your personal data, please contact us through the support options available in the app.',
                ],
            ],
            [
                'heading' => 'Cookies & Local Storage',
                'paragraphs' => [
                    'GullakPe stores a small amount of information in your browser, such as your selected display language, so your preferences are remembered on your next visit. We do not use this storage for advertising or tracking.',
                ],
            ],
            [
                'heading' => 'Children\'s Privacy',
                'paragraphs' => [
                    'GullakPe is intended for users who are at least 18 years old. We do not knowingly collect personal information from children.',
                ],
            ],
            [
                'heading' => 'Changes to This Policy',
                'paragraphs' => [
                    'We may update this Privacy Policy from time to time to reflect changes in our practices. Continuing to use GullakPe after changes are posted means you accept the updated policy.',
                ],
            ],
            [
                'heading' => 'Contact Us',
                'paragraphs' => [
                    'If you have questions about this Privacy Policy or how your data is handled, please reach out to us through the support options available in the app.',
                ],
            ],
        ];
    @endphp

    <div class="mt-6 mb-8">
        <h1 class="text-[26px] font-black text-[#1a153a] font-poppins tracking-tight">Privacy Policy</h1>
        <p class="text-[13px] text-slate-400 font-semibold mt-1">Last updated 18 July 2026</p>
    </div>

    <div class="flex flex-col gap-7 pb-16">
        @foreach ($sections as $i => $section)
            <div>
                <h2 class="text-[16px] font-black text-[#0A5C66] font-poppins tracking-tight mb-2">
                    <span class="text-slate-300 mr-1.5">{{ $i + 1 }}.</span>{{ $section['heading'] }}
                </h2>
                <div class="flex flex-col gap-2.5">
                    @foreach ($section['paragraphs'] as $paragraph)
                        <p class="text-[13.5px] text-slate-600 font-medium leading-relaxed">{{ $paragraph }}</p>
                    @endforeach
                </div>
            </div>
        @endforeach

        <div class="flex items-start gap-2.5 bg-slate-50 border border-slate-100 rounded-[14px] p-4 mt-2">
            <i class="fa-solid fa-shield-halved text-[13px] text-slate-400 mt-0.5"></i>
            <p class="text-[12px] text-slate-500 font-medium leading-relaxed">We take the security of your financial information seriously and continue to improve how we protect it.</p>
        </div>
    </div>

@endsection
